#!/usr/bin/env php
<?php
use LaravelComposer\NewCommand;
use Symfony\Component\Console\Application;

if (file_exists(__DIR__.'/vendor/autoload.php'))
{
    require __DIR__.'/vendor/autoload.php';
}
else
{
    require __DIR__.'/../../autoload.php';
}

$app = new Application('Laravel composer', '0.1');
$app->add(new NewCommand);
$app->run();
